# Generated by Django 5.1.4 on 2026-09-26 12:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=16)),
                ('stage', models.CharField(choices=[('PENDING', 'Pending'), ('LOAD', 'Load'), ('LLM', 'Llm'), ('VALIDATE', 'Validate'), ('TRANSFORM', 'Transform'), ('WRITE', 'Write'), ('DONE', 'Done')], default='PENDING', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('connection_id', models.UUIDField()),
                ('bucket', models.CharField(max_length=255)),
                ('file_key', models.CharField(max_length=1024)),
                ('transform_type', models.CharField(choices=[('REPLACE', 'Find pattern and replace with a fixed value'), ('EXTRACT', 'Extract the matched pattern into a new column'), ('NORMALIZE', 'Rewrite matches into a normalized format')], max_length=16)),
                ('prompt', models.TextField()),
                ('replacement', models.TextField(blank=True, default='')),
                ('columns', models.JSONField(default=list)),
                ('new_column_name', models.CharField(blank=True, default='', max_length=255)),
                ('regex_pattern', models.TextField(blank=True, default='')),
                ('replacement_template', models.TextField(blank=True, default='')),
                ('llm_explanation', models.TextField(blank=True, default='')),
                ('llm_cache_hit', models.BooleanField(default=False)),
                ('row_count', models.BigIntegerField(blank=True, null=True)),
                ('matched_rows', models.BigIntegerField(blank=True, null=True)),
                ('result_path', models.CharField(blank=True, default='', max_length=1024)),
                ('result_columns', models.JSONField(blank=True, default=list)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
